from __future__ import annotations
from typing import Protocol, Any

class EngineAdapter(Protocol):
    @property
    def tick(self) -> int: ...
    def advance_to(self, tick: int) -> None: ...
    def play_card(self, *, side: str, card: str, cell: tuple[int, int]) -> None: ...
    def activate_ability(self, *, side: str, card: str | None) -> None: ...
    def snapshot(self) -> dict[str, Any]: ...
